Multi-Arch Pipeline
TeleVet/actions-workflows pull request #18
Opened 2023-07-13 21:46 UTC by aziz-shoko

This pipeline builds amd64 and arm64 images

2023-07-24 17:43 UTC, jeff-french requested changes

2023-07-24 17:43 UTC, jeff-french commented on .github/workflows/docker-build.yaml
> +          docker buildx imagetools create --tag ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_name }}-multi-arch $AMD64_IMAGE_REF $ARM64_IMAGE_REF
Need to include the commit sha here or else we run the risk of clobbering images or tagging the wrong image due to race conditions.

Make this:
```
docker buildx imagetools create --tag ${{ inputs.registry }}/${{ inputs.image_name }}:sha-${{ github.sha }}-multi-arch $AMD64_IMAGE_REF $ARM64_IMAGE_REF
```

2023-07-24 17:43 UTC, jeff-french commented on .github/workflows/reusable-qa-deploy.yaml
> +name: QA Deployments Reusable Workflow
Why is this being broken apart into multiple files?

2023-07-24 17:43 UTC, jeff-french commented on file.txt
> +***.dkr.ecr.us-east-2.amazonaws.com/core-api:feat-multi-arch
Why is this file here?

2023-07-24 17:55 UTC, aziz-shoko commented on file.txt
> +***.dkr.ecr.us-east-2.amazonaws.com/core-api:feat-multi-arch
Forgot to delete this file, I will delete it.

2023-07-24 17:55 UTC, aziz-shoko commented on .github/workflows/docker-build.yaml
> +          docker buildx imagetools create --tag ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_name }}-multi-arch $AMD64_IMAGE_REF $ARM64_IMAGE_REF
Ok thanks!

2023-07-24 18:00 UTC, aziz-shoko commented on .github/workflows/reusable-qa-deploy.yaml
> +name: QA Deployments Reusable Workflow
because I am a big idiot...
After learning that no steps can be run in the job, for some reason I decided to separated it out to another workflow file instead of just adding another job. Thanks for the review, I will get back to you after I fix it and test it.

2023-07-25 13:05 UTC, jeff-french requested changes

2023-07-25 13:05 UTC, jeff-french commented on .github/workflows/docker-build.yaml
> +            new_image_tag="$image_tag-$random_string"
We want the tags to be deterministic. What issue are you solving with the random string here?

2023-07-25 13:34 UTC, aziz-shoko commented on .github/workflows/docker-build.yaml
> +            new_image_tag="$image_tag-$random_string"
Was getting image already exists errors and I was adding random strings at the end to make them unique. Turns out I was just extracting the wrong manifest. Those lines are not actually suppose to be there because in the actual command, I was using the $image_tag variable 
```aws ecr put-image --repository-name ${{ inputs.image_name }} --image-tag "$image_tag" --image-manifest "$IMAGE_MANIFEST"```
I will remove those lines

2023-07-27 19:03 UTC, closed without merging