Separate Workflow for Release Tags
TeleVet/actions-workflows pull request #25
Opened 2023-09-22 16:01 UTC by aziz-shoko

We are currently getting the error below when we are trying to create a new-release tag:
[https://github.com/TeleVet/pawblisher/actions/runs/6240655444](https://github.com/TeleVet/pawblisher/actions/runs/6240655444)

To fix it, we will have a separate workflow for tagging images with the release tag.

2023-09-22 19:34 UTC, jeff-french requested changes

2023-09-22 19:34 UTC, jeff-french commented on .github/workflows/docker-build.yaml
> +            if [[ $? != 0 ]]; then
This looks like it's just going to push the image tag as long as the last command didn't exit with an error. I don't see where it's actually checking the results from the `IMAGE_META` above. Did you test that this correctly skips images that are already present?

2023-09-22 19:34 UTC, jeff-french commented on .github/workflows/release-tags.yaml
> +            echo "Image with commit SHA $COMMIT_SHA not found."
If it can't find an image to tag then it needs to fail the build.

2023-09-22 19:34 UTC, jeff-french commented on .github/workflows/release-tags.yaml
> +          IMAGE_META="$(aws ecr describe-images --repository-name=${{ inputs.image_name }} --image-ids=imageTag=$COMMIT_SHA 2> /dev/null)"
The images get tagged in the the regular build process with a docker tag like `sha-$COMMIT_SHA` so that's what we need to be checking for here.

2023-09-22 19:59 UTC, aziz-shoko commented on .github/workflows/docker-build.yaml
> +            if [[ $? != 0 ]]; then
The ticket from JIRA had this script posted
[https://gist.github.com/outofcoffee/8f40732aefacfded14cce8a45f6e5eb1](https://gist.github.com/outofcoffee/8f40732aefacfded14cce8a45f6e5eb1)
So I used the same idea here

2023-09-22 20:05 UTC, aziz-shoko commented on .github/workflows/docker-build.yaml
> +            if [[ $? != 0 ]]; then
I will test it just to make sure its good to go

2023-09-29 17:11 UTC, jeff-french approved these changes

2023-09-29 18:09 UTC, merged